let handler = async (m, { conn, usedPrefix }) => conn.sendButton(m.chat, `“${spill.getRandom()}”`, author, ['SPILL', `${usedPrefix}spill di`], m)

handler.help = ['spill']
handler.tags = ['spill or drink']
handler.command = /^(spill)$/i

export default handler


// https://jalantikus.com/tips/kata-kata-bucin/
const spill = [
    "spill siapa adek kesayangan lu",
    "Spill musuh lu di rpw?",
    "BAGAIMANA PERASAANMU KETIKA KAMU NGECHAT DIREAD DOANG",
    "Spill bestie lwan jnis lu yng bkin lu tkut kehilangan",
    "Spill film indo fav",
    "Spill siapa yg ada di dalam hatimu",
    "Spill orang yg gatau malu",
    "kenangan sama mantan yang ga bisa dilupain?",
    "spill orang paling lemot disini",
    "Spill chr yg ngajakin lu nikah",
    "spill yang menurut kamu paling cantik disini tag orang nya",
    "Pernah nyakitin cp kamu? Ceritain",
    "spill orang teralay yg lu knal",
    "spill yg sering kamu chat",
    "Spill aplikasi favorit",
    "spill yang paling emosian tag orang nya",
    "spill kenapa cowo banyak yang dingin",
    "Sebutin nama mantan berserta charanya !",
    "spill org yg pling uwuphobia siapa ?",
    "spill yg bisa liat last seen lu",
    "spill yang menurut kamu paling ganteng disini ( tag )",
    "spill chat terbucin sama mantan",
    "Spill lo pernah ga diam² pacaran di rp, pdhl di rl lo punya pacar?",
    "spill semua chara mantan",
    "Pernah ada fambest yg nyebar rl ga ?",
    "Spill yang sedang bucin",
    "spill yang sering minta jatah",
    "Spill lagu sering didengerin di spotify",
    "spill semua nama orang yg sempat bikin kamu kecewa",
    "Spill chara favorit di rp",
    "spill mantan terkrik",
    "Spill chat 21+ sama cp",
    "spill yg kaya monyet",
    "spill yg suka ngasih harapan palsu",
    "Spill fambest ter sange",
    "spill list gebetan",
    "spill pernah naena sama org selain pacar ga",
    "spill musuh bebuyutan lu",
    "spill pernah ga sahabat lu di rebut?",
    "Spill orang(nama) Yg Ciri Ciri nya Masuk Sama Ciri2 Pacar Idaman",
    "nama mantan pertama?",
    "spill abang yang lo pengen jadiin dia cp",
    "Spill masalah lu ama fambest baru2 ini",
    "Spill yg sering ditinggal pas lagi sange sange nya",
    "spill pernah ga lu ada niatan selingkuh pas masih punya cp? alasannya?",
    "Spill wallpaper WhatsApp",
    "spill orang terjamet",
    "Spill lagu yg buat nangis",
    "Temen yg suka nikung itu enaknya diapain?",
    "Spill pernah nonton hentai gk",
    "spill lu pernah bohong sm cp? krn ap",
    "spill pernah belok ga?",
    "Spill chat yang sering di hubungi",
    "Spill jjkp",
    "Spill kapan terakhir ngewe",
    "spill yang paling nyeremin disini (tag)",
    "Spill menunggu atau menanti?",
    "spill yg ga bisa ditinggal sebentar sama cp nya",
    "Spill yang lagi kena adek kakak zone",
    "Spill hal ternakal yg pernah lu lakuin di rp",
    "spill warna celana dalammu",
    "Spill imejin ngewe",
    "Spill pernah di duain?",
    "spill akun tiktok yang lu pegang",
    "spill pernah cepu ga?",
    "spill orang yang menurut lo caper banget",
    "spill apa yang paling di benci",
    "spill pernah ditinggal pas lagi ngewe atau ga?",
    "spill ngecrushin sp? klo bisa tag",
    "Spill yang paling king drama di gc ini ( tag )",
    "Spill kencan idaman",
    "Spill orang yang lagi ribut sama lu?",
    "Gimana rasanya cinta bertepuk sebelah tangan?",
    "Spill lu lagi ngapain",
    "Spill hari terburuk lo",
    "SPILL CHATTAN UWU SAMA MANTAN",
    "spill siapa sering typo",
    "spill pernah ga sahabat lu di rebut?",
    "Spill adek tergemes yg kamu punya",
    "spill cowok tercuek",
    "Spill pernah ngambil gebetan temen sendiri ga",
    "spill nama di akun lilspes ( klo pernah )",
    "spill pernah ngapain aja sama pacar",
    "Cara biar gak mati topik Ama cp",
    "Spill warna gagang pintu rumah tetangga lo",
    "spill copy paste terakhir",
    "Spill awal lu newbie",
    "spill yg masih ngarep orang",
    "spill kata paling kotor yang pernah diucapin",
    "Spill yg makanan kesukaan",
    "Spill chr + nn yang pernah nikung luh",
    "spill arsip chat",
    "Sering kangen mantan rp ga?",
    "spill ch yang pernah lo plagiatin",
    "Spill masalah terbesar lu di rp",
    "spill orang pemes",
    "Spill pernah tuker pap ga",
    "spill chat yg bikin salting.",
    "Spill cp Rp pertama",
    "spill judul lagu yg ngegambarin perasaan sekarang",
    "lagu apa yang buat lo sedih?",
    "spill chr terfavorite",
    "spill kado ulang tahun paling the best",
    "Spill pernah pura2 gatau mantan nge klon apa engga",
    "spill perkataan yang paling nyakitin",
    "Spill bestai paling disayang",
    "Spill sifat cp lu",
    "Temen yg suka nikung itu enaknya diapain?",
    "spill nama mantan crush lu",
    "spill orang yang lu 'have a crush' siapa tau jadian (tag)",
    "spill phobia Kamu",
    "Spill sapa yang suka toxic",
    "Spill hal terbejat yg pernah lu lakuin pas cpan",
    "Spill musuh bebuyutan",
    "Spill pernah gak kepikiran buat lanjut hubungan sama cp di rl?",
    "spill lagu yang bikin keinget sama orang, spill nama orangnya juga",
    "Spill hal terandom yg pernah dipikirin",
    "spill orng yg paling lu gasuka disini",
    "spill mending temenan aja atau cp an ?",
    "spill tukang boong",
    "spill pernah baper sampe rl?",
    "spill hal yg bikin lu ga nyaman di gc ini",
    "tag orang yang paling gatau diri",
    "Bosen gk sama Gc ini?",
    "Spill kenapa lu slr?",
    "spill yang paling pendiem (tag)",
    "pernah bestie rprl an gak? kalo pernah tag",
    "spill mantan yang paling bikin lu gak bisa move on sampai sekarang",
    "spill orang yang pernah nyakitin lo",
    "spill siapa disini yang paling daddyable?",
    "spill yg suka fitnah",
    "spill yang paling soft di gc",
    "Spill apa yang kamu pikirin sekarang",
    "spill apa yang bikin lu gamon/nyari cowo yang mirip mantan",
    "Spill pengalaman terhoror"
]